define block0 model
(
  size [50.00 0.500 0.7500]
  gui_nose 0
  name "obstacle0"
  color "black"	
)

define block1 model
(
  size [1.00 0.500 0.7500]
  gui_nose 0
  name "obstacle1"
  color "black"	
)

define block2 model
(
  size [2.00 0.500 0.7500]
  gui_nose 0
  name "obstacle2"
  color "black"	
)

define block3 model
(
  size [5.00 0.500 0.7500]
  gui_nose 0
  name "obstacle3"
  color "black"	
)

define block4 model
(
  size [10.00 0.500 0.7500]
  gui_nose 0
  name "obstacle4"
  color "black"	
)

define block5 model
(
  size [15.00 0.500 0.7500]
  gui_nose 0
  name "obstacle5"
  color "black"	
)

define block6 model
(
  size [20.00 0.500 0.7500]
  gui_nose 0
  name "obstacle6"
  color "black"	
)

define block7 model
(
  size [25.00 0.500 0.7500]
  gui_nose 0
  name "obstacle7"
  color "black"	
)

define block8 model
(
  size [1.00 0.500 0.7500]
  gui_nose 0
  name "obstacle8"
  color "green"	
)

define block9 model
(
  size [0.500 1.00 0.7500]
  gui_nose 0
  name "obstacle9"
  color "yellow"	
)

define block10 model
(
  size [2.00 0.500 0.7500]
  gui_nose 0
  name "obstacle10"
  color "blue"	
)

define block11 model
(
  size [0.500 2.000 0.7500]
  gui_nose 0
  name "obstacle7"
  color "red"	
)